### ISSUE TITLE
YCSwipeMenu item无法点击

### ISSUE THREAD

**Issue by 869238519** [yangchong211/YCRefreshView#2]
当item设置为侧滑布局（YCSwipeMenu）时，item无法点击

**Comment by yangchong211** [comment]
当item设置未侧滑布局的时候，item无法点击是指，删除和置顶无法点击还是整个item无法点击？
当处于侧滑布局时，点击删除和置顶以外的item位置，则直接关闭侧滑布局
当处于侧滑布局时，点击删除则是删除该item，点击置顶则是将该item置顶

**Comment by 869238519** [comment]
> 当项目设置未侧滑布局的时候，项目无法点击是指，删除和置顶无法点击还是整个项目无法点击？
> 当处于侧滑布局时，点击删除和置顶以外的项目位置，直接则关闭侧滑布局
> 当处于侧滑布局时，点击删除则是删除该项目，点击置顶则是将该项目置顶

当我设置侧滑布局时，没有在侧滑状态下，点击item我需要进入到我的二级页面去，但是监听不到整个item的点击事件。
